language: node_js

node_js:
  - '8'
  - '10'

before_install:
    - npm install
    - cd electron-app
    - npm install
    - cd ..

install:
    - npm install -g codecov

script:
    - npm run test
    - codecov
    - npm run web:build
    - npm run app:build:linux
