language: node_js

node_js:
  - '8'
  - '10'

install:
    - npm install
    - cd electron-app
    - npm install
    - cd ..

script:
    - npm run test
    - npm run codecov
    - npm run web:build
    - npm run app:build:linux
