language: node_js

node_js:
  - '6'
  - '7'

before_install:
    - npm install
    - cd electron-app
    - npm install
    - cd ..

script:
    - npm run test
    - npm run web:build
    - npm run app:build:linux
