export const ROUTER_LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

export const TOGGLE_LEFT_DRAWER = 'TOGGLE_LEFT_DRAWER';
export const TOGGLE_NEW_COLLECTION_DIALOG = 'TOGGLE_NEW_COLLECTION_DIALOG';
export const TOGGLE_EDIT_COLLECTION_DIALOG = 'TOGGLE_EDIT_COLLECTION_DIALOG';
export const TOGGLE_REMOVE_COLLECTION_DIALOG = 'TOGGLE_REMOVE_COLLECTION_DIALOG';

export const ADD_NEW_COLLECTION = 'ADD_NEW_COLLECTION';
export const SAVE_COLLECTION_TITLE = 'SAVE_COLLECTION_TITLE';
export const REMOVE_COLLECTION = 'REMOVE_COLLECTION';

export const ADD_NEW_COLLECTION_LINK = 'ADD_NEW_COLLECTION_LINK';
export const SAVE_COLLECTION_LINK = 'SAVE_COLLECTION_LINK';
export const MOVE_COLLECTION_LINK_UP = 'MOVE_COLLECTION_LINK_UP';
export const REMOVE_COLLECTION_LINK = 'REMOVE_COLLECTION_LINK';

export const COLLECTION_STARTED_PLAYING = 'COLLECTION_STARTED_PLAYING';
export const PLAY_NEXT_LINK = 'PLAY_NEXT_LINK';

export default {
    ROUTER_LOCATION_CHANGE,
    TOGGLE_LEFT_DRAWER,
    TOGGLE_NEW_COLLECTION_DIALOG,
    TOGGLE_EDIT_COLLECTION_DIALOG,
    TOGGLE_REMOVE_COLLECTION_DIALOG,
    ADD_NEW_COLLECTION,
    SAVE_COLLECTION_TITLE,
    REMOVE_COLLECTION,
    ADD_NEW_COLLECTION_LINK,
    SAVE_COLLECTION_LINK,
    MOVE_COLLECTION_LINK_UP,
    REMOVE_COLLECTION_LINK,
    COLLECTION_STARTED_PLAYING,
    PLAY_NEXT_LINK,
};
