export const TOGGLE_LEFT_DRAWER = 'TOGGLE_LEFT_DRAWER';
export const TOGGLE_NEW_COLLECTION_DIALOG = 'TOGGLE_NEW_COLLECTION_DIALOG';

export const ADD_NEW_COLLECTION = 'ADD_NEW_COLLECTION';
export const ADD_NEW_COLLECTION_LINK = 'ADD_NEW_COLLECTION_LINK';
export const MOVE_COLLECTION_LINK_UP = 'MOVE_COLLECTION_LINK_UP';
